#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Disable autocorrect guesses.
unsetopt CORRECT

PROMPT="%F{magenta}%n%f@%F{yellow}%m%f %F{green}%~%f ${git_info:+${(e)git_info[prompt]}}$ "

# Autocomplete for '..'
zstyle -e ':completion:*' special-dirs '[[ $PREFIX = (../)#(|.|..) ]] && reply=(..)'

# LS colors
export CLICOLOR=1
export LSCOLORS=gxfxcxdxcxegedabagacad

# Language environment
export LANG=en_US.UTF-8
#export LC_ALL=C

# Default editor
export EDITOR='vim'

# Aliases
alias zshconfig="$EDITOR ~/.zshrc"
alias ll="ls -lh"
alias la="ls -A"
